CREATE TABLE IF NOT EXISTS  journals
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	INT time_in NOT NULL,
	INT time_in NOT NULL,
	INT auto_id NOT NULL,
	INT route_id NOT NULL
FOREIGN KEY (route_id)
REFERENCES routes(id)
ON DELETE CASCADE
);